default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: password
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: haraherhythm_develop

test:
  <<: *default
  database: haraherhythm_test

staging:
  <<: *default
  database: <%= ENV['APP_DATABASE_URL'] %>
  host: <%= ENV['APP_DATABASE_HOST'] %>
  username: <%= ENV['APP_DATABASE_USER'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

production:
  <<: *default
